/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import java.awt.CardLayout;



/**
 *
 * @author AndreasStensig
 */
public class GraphicalUserInterface extends javax.swing.JPanel {

    private final CardLayout layout;
    private final GUITicket ticketPanel;
    private final GUIFrontpage frontPagePanel;
    
    /**
     * Creates new form GraphicalUserInterface
     */
    public GraphicalUserInterface() {
        initComponents();
        layout = new CardLayout();
        this.setLayout(layout);
        
        frontPagePanel = new GUIFrontpage(this);
        ticketPanel = new GUITicket(this);
        this.add(frontPagePanel, "Front");
        this.add(ticketPanel, "Ticket");
    }

    public void switchPanel(String target) {
        if (target.equals("Ticket")) {
            ticketPanel.loadTicketData();
        }        
        layout.show(this, target);
    }
    
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMinimumSize(new java.awt.Dimension(250, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
