/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import javax.swing.JOptionPane;



/**
 *
 * @author Stensig
 */
public class GUIFrontpage extends javax.swing.JPanel {

    private final GraphicalUserInterface parent;
    
    /**
     * Creates new form GUIAppFrontpage
     * @param parent the parent container for the <code>JLabel</code>.
     */
    public GUIFrontpage(GraphicalUserInterface parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * Show the lable on the front page informing the user that the application
     * has recieved and responded to a ping. 
     * @param show true if the lable should be shown, false otherwise. 
     */
    public void showPingLable(boolean show) {
        labPDASeen.setVisible(show);
    }
    
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShowTicket = new javax.swing.JButton();
        btnRoutePlanner = new javax.swing.JButton();
        labPDASeen = new javax.swing.JLabel();
        btnEndJourney = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(250, 400));
        setPreferredSize(new java.awt.Dimension(250, 400));

        btnShowTicket.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnShowTicket.setText("Show Ticket");
        btnShowTicket.setPreferredSize(new java.awt.Dimension(150, 75));
        btnShowTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowTicketActionPerformed(evt);
            }
        });

        btnRoutePlanner.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoutePlanner.setText("Route Planner");
        btnRoutePlanner.setPreferredSize(new java.awt.Dimension(150, 75));
        btnRoutePlanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoutePlannerActionPerformed(evt);
            }
        });

        labPDASeen.setForeground(new java.awt.Color(51, 102, 0));
        labPDASeen.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labPDASeen.setText("Your device has been registered.");
        labPDASeen.setFocusable(false);

        btnEndJourney.setText("End Journey");
        btnEndJourney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEndJourneyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labPDASeen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRoutePlanner, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEndJourney)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEndJourney, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnShowTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnRoutePlanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(labPDASeen)
                .addContainerGap())
        );

        labPDASeen.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowTicketActionPerformed
        parent.switchPanel("Ticket");
    }//GEN-LAST:event_btnShowTicketActionPerformed

    private void btnRoutePlannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoutePlannerActionPerformed
        String message = "Redirecting to browser. . .";
        String title = "Route Planner redirect";
        JOptionPane.showMessageDialog(this, message, title,
                                      JOptionPane.INFORMATION_MESSAGE);
        // Go to website
    }//GEN-LAST:event_btnRoutePlannerActionPerformed

    private void btnEndJourneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEndJourneyActionPerformed
        String title = "Exit application";
        String msg = "Are you sure you want to \nend your journey?";
        int end = JOptionPane.showConfirmDialog(parent, msg, title, JOptionPane.YES_NO_OPTION);
        if (end == JOptionPane.YES_OPTION) {
            System.out.println("Client closing app. . . ");
            System.exit(1);
        }
    }//GEN-LAST:event_btnEndJourneyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEndJourney;
    private javax.swing.JButton btnRoutePlanner;
    private javax.swing.JButton btnShowTicket;
    private javax.swing.JLabel labPDASeen;
    // End of variables declaration//GEN-END:variables
}
