package FrontEnd;

import BuisnessLogic.Ticket;



/**
 *
 * @author AndreasStensig 14/11/2014
 */
public class GUITicket extends javax.swing.JPanel {

    private final GraphicalUserInterface parent;
    
    /**
     * Creates new form GUITicket
     * @param parent the parent container for the <code>JLabel</code>.
     */
    public GUITicket(GraphicalUserInterface parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * Load the data from a <code>Ticket</code> object into the gui panel
     * displaying the ticket. 
     * @param ticket the ticket with the information. 
     */
    public void loadTicketData(Ticket ticket) {
        // Load ticket from PDAAplication
        String cusNum = "" + ticket.getCustomerNumber();
        String time = ticket.getTimestamp();
        String price = "" +  (ticket.getPrice() / 100); // øre to dkk
        String startZone = "" +  ticket.getStartZone();
        String tickNum = "" + ticket.getNumber();
        fieldCusNum.setText(cusNum);
        fieldTime.setText(time);
        fieldPrice.setText(price);
        fieldStartZone.setText(startZone);
        fieldTickNum.setText(tickNum);
    }
    
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        labCusNum = new javax.swing.JLabel();
        fieldCusNum = new javax.swing.JTextField();
        labTime = new javax.swing.JLabel();
        fieldTime = new javax.swing.JTextField();
        labPrice = new javax.swing.JLabel();
        fieldPrice = new javax.swing.JTextField();
        labStartZone = new javax.swing.JLabel();
        fieldStartZone = new javax.swing.JTextField();
        labTickNum = new javax.swing.JLabel();
        fieldTickNum = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(250, 400));

        btnBack.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        labCusNum.setText("Customer Number");

        fieldCusNum.setText(" ");
        fieldCusNum.setFocusable(false);

        labTime.setText("Time");

        fieldTime.setText(" ");
        fieldTime.setFocusable(false);

        labPrice.setText("Price (DKK)");

        fieldPrice.setFocusable(false);

        labStartZone.setText("Start zone");

        fieldStartZone.setFocusable(false);

        labTickNum.setText("Ticket Number");

        fieldTickNum.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldTime)
                    .addComponent(fieldCusNum)
                    .addComponent(fieldPrice)
                    .addComponent(fieldStartZone)
                    .addComponent(fieldTickNum)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCusNum)
                            .addComponent(labTime)
                            .addComponent(labPrice)
                            .addComponent(labStartZone)
                            .addComponent(labTickNum))
                        .addGap(0, 127, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labCusNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldCusNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labStartZone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldStartZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labTickNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldTickNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        parent.switchPanel("Front");
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField fieldCusNum;
    private javax.swing.JTextField fieldPrice;
    private javax.swing.JTextField fieldStartZone;
    private javax.swing.JTextField fieldTickNum;
    private javax.swing.JTextField fieldTime;
    private javax.swing.JLabel labCusNum;
    private javax.swing.JLabel labPrice;
    private javax.swing.JLabel labStartZone;
    private javax.swing.JLabel labTickNum;
    private javax.swing.JLabel labTime;
    // End of variables declaration//GEN-END:variables
}
