package FrontEnd;

import javax.swing.JOptionPane;


/**
 * Front page <code>JPanel</code> for the customer PDA application GUI.
 * <p>
 * @author Andreas Stensig Jensen on Nov 5th, 2014
 * Contributors:
 */
public class GUIFrontpage extends javax.swing.JPanel {

    private final GraphicalUserInterface parent;
    private boolean journeyStatus = true;

    /**
     * Creates new form GUIAppFrontpage
     * <p>
     * @param parent the parent container for this element.
     */
    public GUIFrontpage(GraphicalUserInterface parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * Show the label on the front page informing the user that the application
     * has received and responded to a ping.
     * <p>
     * @param show true if the label should be shown, false otherwise.
     */
    public void showPingLable(boolean show) {
        labPDASeen.setVisible(show);
    }
    
    /**
     * Show in the GUI that journeying is once again enabled. 
     */
    public void displayEnableJourneying() {
        journeyStatus = true;
        btnJourneyStatus.setText("End Journey");
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShowTicket = new javax.swing.JButton();
        btnRoutePlanner = new javax.swing.JButton();
        labPDASeen = new javax.swing.JLabel();
        btnJourneyStatus = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(250, 400));
        setPreferredSize(new java.awt.Dimension(250, 400));

        btnShowTicket.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnShowTicket.setText("Show Ticket");
        btnShowTicket.setPreferredSize(new java.awt.Dimension(150, 75));
        btnShowTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowTicketActionPerformed(evt);
            }
        });

        btnRoutePlanner.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRoutePlanner.setText("Route Planner");
        btnRoutePlanner.setPreferredSize(new java.awt.Dimension(150, 75));
        btnRoutePlanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoutePlannerActionPerformed(evt);
            }
        });

        labPDASeen.setForeground(new java.awt.Color(51, 102, 0));
        labPDASeen.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        labPDASeen.setText("Your device has been registered.");
        labPDASeen.setFocusable(false);

        btnJourneyStatus.setText("End Journey");
        btnJourneyStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJourneyStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labPDASeen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRoutePlanner, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnShowTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnJourneyStatus)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnJourneyStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnShowTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnRoutePlanner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(labPDASeen)
                .addContainerGap())
        );

        labPDASeen.setVisible(false);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Switch to the ticket panel for viewing the currently active ticket.
     * <p>
     * @param evt not used.
     */
    private void btnShowTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowTicketActionPerformed
        parent.switchPanel("Ticket");
    }//GEN-LAST:event_btnShowTicketActionPerformed

    /**
     * Simulate switching to the browser of the PDA in order to redirect to the
     * site containing the route planner module.
     * <p>
     * @param evt not used.
     */
    private void btnRoutePlannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoutePlannerActionPerformed
        String message = "Redirecting to browser. . .";
        String title = "Route Planner redirect";
        JOptionPane.showMessageDialog(this, message, title,
                                      JOptionPane.INFORMATION_MESSAGE);
        /* In a propper implementation, switch to browser application */
    }//GEN-LAST:event_btnRoutePlannerActionPerformed

    /**
     * Let the user end the journey disabling the ping handler. The handler will
     * then be inactive for a fixed time before reactivating automatically. 
     * <p>
     * The user may also use this button again, when the handler is inactive, to
     * reactivate it and enable journeying again.
     * <p>
     * @param evt not used.
     */
    private void btnJourneyStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJourneyStatusActionPerformed
        String title = "Confirmation";
        String msg = "Are you sure?";
        int answer = JOptionPane.showConfirmDialog(parent, msg, title,
                                                JOptionPane.YES_NO_OPTION);
        if (answer == JOptionPane.YES_OPTION) {
            if (journeyStatus) {
                journeyStatus = false;
                parent.enableJourney(journeyStatus);
                showPingLable(false);
                btnJourneyStatus.setText("Begin Journey");
            } else {
                journeyStatus = true;
                parent.enableJourney(journeyStatus);
                btnJourneyStatus.setText("End Journey");
            }
        }
    }//GEN-LAST:event_btnJourneyStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJourneyStatus;
    private javax.swing.JButton btnRoutePlanner;
    private javax.swing.JButton btnShowTicket;
    private javax.swing.JLabel labPDASeen;
    // End of variables declaration//GEN-END:variables
}
